// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"github.com/mazrean/kessoku"
	"net/http"
)

func NewApp() *App {
	app := kessoku.Provide(func() *App {
		return &App{httpsrv: &http.Server{Addr: "localhost:6060"}}
	}).Fn()()
	return app
}
