// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"net/http"

	"github.com/mazrean/kessoku"

	"github.com/jr-dragon/tephroite/internal/server"
)

func NewApp() *App {
	respserver := kessoku.Provide(server.NewRESPServer).Fn()()
	app := kessoku.Provide(func(respsrv *server.RESPServer) *App {
		return &App{httpsrv: &http.Server{Addr: "localhost:6060"}, respsrv: respsrv}
	}).Fn()(respserver)
	return app
}
